name: Update IMDb Top TV List

on:
  schedule:
    - cron: '0 3 * * *'      # every day at 03:00 UTC
  workflow_dispatch:          # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate top 25 JSON list (with TVDB IDs)
        run: |
          python generate_list.py -n 25 -o top_25.json

      - name: Generate top 10 JSON list (with TVDB IDs)
        run: |
          python generate_list.py -n 10 -o top_10.json

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Refresh top‑25 IMDb → TVDB list"
          file_pattern: top_25.json