name: Update IMDb Top TV List

# Triggers
on:
  schedule:
    - cron: '0 3 * * *'        # daily at 03:00 UTC
  workflow_dispatch:           # enable manual runs from the UI

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # needed for the commit push

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ Install dependencies
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Run the script (produces top_25.json)
      - name: Generate JSON list
        run: |
          python generate_list.py -n 25 -o top_25.json

      # 5️⃣ Commit & push if file changed
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Update top‑25 IMDb TV list"
          file_pattern: top_25.json
          # optional: only commit if there are changes
          # (the action does this automatically)